# coding: utf-8
a.dat
open("a.dat")
get_ipython().run_line_magic('pwd', '')
get_ipython().run_line_magic('cat', 'a.dat')
f = open ("a.dat")
whatis f
f = open ("a.dat")
type(f)
f.close()
get_ipython().run_line_magic('cat', 'a.dat')
f.close()
f = open ("a.dat")
f.
f.readlines
f.readlines()
f.readlines()
f.readlines()
f.close()
f.readlines()
f.readlines()
f.close()
s = f.readlines()
f = open ("a.dat")
s = f.readlines()
f.close()
s
print(s)
print(s+S)
print(s+s)
s
print(s+s)
print(s+s)
s[0]
f.close()
f = open ("a.dat")
f.tell()
s = f.readlines()
f.tell()
f.seek
f.seek(0)
f.readlines()
f.readlines()
f.seek(0)
f.readlines()
f.seek(3)
f.readlines()
f.seek(2)
f.readlines()
f.seek(1,4)
f.seek(0)
f.close
f.close(0)
f.close()
f = open ("a.dat", "r")
f.readlines()
f.close()
f = open ("a.dat", "w")
f.write("EDIBO")
f.close
f.close()
f = open ("a.dat", "w")
f.write()
f.write("EDIBO\n")
f.close()
f.write("EDIBO\n")
f.closed
f = open ("a.dat", "w")
f.closed
f.write("\n\n\tEDIBO\n")
f.closed()
f.close()
f = open ("a.dat", "a")
f.write("\n EDIBO \n")
f.write("\n 2020 \n")
f.close()
get_ipython().run_line_magic('save', 'jaunais13 1-76')
